In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [1]:
import pandas as pd

In [2]:
https://drive.google.com/file/d/1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_/view?usp=sharing

SyntaxError: invalid decimal literal (1183269077.py, line 1)

In [3]:
!gdown 1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_

'gdown' is not recognized as an internal or external command,
operable program or batch file.

In [4]:
df = pd.read_csv('smoker_bill.csv') #storing the data in df
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [5]:
type(df)

pandas.core.frame.DataFrame

In [6]:
df['country']

KeyError: 'country'

In [ ]:
type(df['country'])

pandas.core.series.Series

In [ ]:
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
#top 5 rows
df.head() #top5 rows by default

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [ ]:
#top 10 rows from my data
df.head(10)

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106
5  Afghanistan  1977    14880372      Asia    38.438  786.113360
6  Afghanistan  1982    12881816      Asia    39.854  978.011439
7  Afghanistan  1987    13867957      Asia    40.822  852.395945
8  Afghanistan  1992    16317921      Asia    41.674  649.341395
9  Afghanistan  1997    22227415      Asia    41.763  635.341351

In [ ]:
df.head?

In [ ]:
#bottom rows
df.tail() #5 bottom rows by default

       country  year  population continent  life_exp     gdp_cap
1699  Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700  Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701  Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702  Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703  Zimbabwe  2007    12311143    Africa    43.487  469.709298

In [ ]:
#3 bottom rows
df.tail(3)

       country  year  population continent  life_exp     gdp_cap
1701  Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702  Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703  Zimbabwe  2007    12311143    Africa    43.487  469.709298

In [ ]:
#rows and columns ?
df.shape

(1704, 6)

In [ ]:
#basic operations on columns
#add a new column
#delete a column
#rename any column

In [ ]:
df.columns

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap'], dtype='object')

In [ ]:
df.keys()

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap'], dtype='object')

In [ ]:
#access a single column
df['country']

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...
1699       Zimbabwe
1700       Zimbabwe
1701       Zimbabwe
1702       Zimbabwe
1703       Zimbabwe
Name: country, Length: 1704, dtype: object

In [ ]:
#if i want 20 top rows only
df['country'].head(20)

0     Afghanistan
1     Afghanistan
2     Afghanistan
3     Afghanistan
4     Afghanistan
5     Afghanistan
6     Afghanistan
7     Afghanistan
8     Afghanistan
9     Afghanistan
10    Afghanistan
11    Afghanistan
12        Albania
13        Albania
14        Albania
15        Albania
16        Albania
17        Albania
18        Albania
19        Albania
Name: country, dtype: object

In [ ]:
#access multiple columns
df[['country','life_exp']].head()

       country  life_exp
0  Afghanistan    28.801
1  Afghanistan    30.332
2  Afghanistan    31.997
3  Afghanistan    34.020
4  Afghanistan    36.088

In [ ]:
#unique countries that have been surveyed ?
df['country'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
       'Australia', 'Austria', 'Bahrain', 'Bangladesh', 'Belgium',
       'Benin', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon',
       'Canada', 'Central African Republic', 'Chad', 'Chile', 'China',
       'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Czech Republic',
       'Denmark', 'Djibouti', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Ethiopia',
       'Finland', 'France', 'Gabon', 'Gambia', 'Germany', 'Ghana',
       'Greece', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Haiti',
       'Honduras', 'Hong Kong, China', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kenya', 'Korea, Dem. Rep.',
       'Korea, Rep.', 'Kuwait', 'Lebanon', 'Lesotho', 'Liberia', 'Libya',
       'Madagascar', 'Malawi', 'Malaysia', 'Mali', 'Mauritania',
       'Mauritius', 'Mexico', 'Mongolia', 'Montenegro', 'Morocco',
       'Mozambique', 'Myanmar', 'Namibia', 'Nepal', 'Netherlands',
       'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Norway', 'Oman',
       'Pakistan', 'Panama', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Puerto Rico', 'Reunion', 'Romania', 'Rwanda',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Sierra Leone', 'Singapore', 'Slovak Republic', 'Slovenia',
       'Somalia', 'South Africa', 'Spain', 'Sri Lanka', 'Sudan',
       'Swaziland', 'Sweden', 'Switzerland', 'Syria', 'Taiwan',
       'Tanzania', 'Thailand', 'Togo', 'Trinidad and Tobago', 'Tunisia',
       'Turkey', 'Uganda', 'United Kingdom', 'United States', 'Uruguay',
       'Venezuela', 'Vietnam', 'West Bank and Gaza', 'Yemen, Rep.',
       'Zambia', 'Zimbabwe'], dtype=object)

In [ ]:
#count for unique countries ?
len(df['country'].unique())

142

In [ ]:
df['country'].nunique()

142

In [ ]:
#1704 => frequeny of every country => count for each country in your data
df['country'].value_counts()

country
Afghanistan           12
Albania               12
Algeria               12
Angola                12
Argentina             12
                      ..
Vietnam               12
West Bank and Gaza    12
Yemen, Rep.           12
Zambia                12
Zimbabwe              12
Name: count, Length: 142, dtype: int64

In [ ]:
#change the name of a column ?
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
df.rename(columns = {'population':'Population','country':'Country'})

          Country  year  Population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
#changes ?
df.rename(columns = {'population':'Population','country':'Country'},inplace=True)

In [ ]:
df

          Country  year  Population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
#change the name using axis
df.rename({'population':'Population','country':'Country'},inplace=True,axis=1)

In [ ]:
df

          Country  year  Population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
df['Country']

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...
1699       Zimbabwe
1700       Zimbabwe
1701       Zimbabwe
1702       Zimbabwe
1703       Zimbabwe
Name: Country, Length: 1704, dtype: object

In [ ]:
df.Country #alternative way of accessing the column => not so popular

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...
1699       Zimbabwe
1700       Zimbabwe
1701       Zimbabwe
1702       Zimbabwe
1703       Zimbabwe
Name: Country, Length: 1704, dtype: object

In [ ]:
#drop any column
df

          Country  year  Population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
df.drop(columns = ['continent'])

          Country  year  Population  life_exp     gdp_cap
0     Afghanistan  1952     8425333    28.801  779.445314
1     Afghanistan  1957     9240934    30.332  820.853030
2     Afghanistan  1962    10267083    31.997  853.100710
3     Afghanistan  1967    11537966    34.020  836.197138
4     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1699     Zimbabwe  1987     9216418    62.351  706.157306
1700     Zimbabwe  1992    10704340    60.377  693.420786
1701     Zimbabwe  1997    11404948    46.809  792.449960
1702     Zimbabwe  2002    11926563    39.989  672.038623
1703     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [ ]:
df.drop('continent',axis=1)

          Country  year  Population  life_exp     gdp_cap
0     Afghanistan  1952     8425333    28.801  779.445314
1     Afghanistan  1957     9240934    30.332  820.853030
2     Afghanistan  1962    10267083    31.997  853.100710
3     Afghanistan  1967    11537966    34.020  836.197138
4     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1699     Zimbabwe  1987     9216418    62.351  706.157306
1700     Zimbabwe  1992    10704340    60.377  693.420786
1701     Zimbabwe  1997    11404948    46.809  792.449960
1702     Zimbabwe  2002    11926563    39.989  672.038623
1703     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [ ]:
df

          Country  year  Population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
df.drop('continent',axis=1,inplace=True)

In [ ]:
df

          Country  year  Population  life_exp     gdp_cap
0     Afghanistan  1952     8425333    28.801  779.445314
1     Afghanistan  1957     9240934    30.332  820.853030
2     Afghanistan  1962    10267083    31.997  853.100710
3     Afghanistan  1967    11537966    34.020  836.197138
4     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1699     Zimbabwe  1987     9216418    62.351  706.157306
1700     Zimbabwe  1992    10704340    60.377  693.420786
1701     Zimbabwe  1997    11404948    46.809  792.449960
1702     Zimbabwe  2002    11926563    39.989  672.038623
1703     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [ ]:
#create a new column
df

          Country  year  Population  life_exp     gdp_cap
0     Afghanistan  1952     8425333    28.801  779.445314
1     Afghanistan  1957     9240934    30.332  820.853030
2     Afghanistan  1962    10267083    31.997  853.100710
3     Afghanistan  1967    11537966    34.020  836.197138
4     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1699     Zimbabwe  1987     9216418    62.351  706.157306
1700     Zimbabwe  1992    10704340    60.377  693.420786
1701     Zimbabwe  1997    11404948    46.809  792.449960
1702     Zimbabwe  2002    11926563    39.989  672.038623
1703     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [ ]:
df

          Country  year  Population  life_exp     gdp_cap
0     Afghanistan  1952     8425333    28.801  779.445314
1     Afghanistan  1957     9240934    30.332  820.853030
2     Afghanistan  1962    10267083    31.997  853.100710
3     Afghanistan  1967    11537966    34.020  836.197138
4     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1699     Zimbabwe  1987     9216418    62.351  706.157306
1700     Zimbabwe  1992    10704340    60.377  693.420786
1701     Zimbabwe  1997    11404948    46.809  792.449960
1702     Zimbabwe  2002    11926563    39.989  672.038623
1703     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [ ]:
df.drop('year',axis=0,inplace=True)

KeyError: "['year'] not found in axis"

In [ ]:
df

          Country  year  Population  life_exp     gdp_cap
0     Afghanistan  1952     8425333    28.801  779.445314
1     Afghanistan  1957     9240934    30.332  820.853030
2     Afghanistan  1962    10267083    31.997  853.100710
3     Afghanistan  1967    11537966    34.020  836.197138
4     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1699     Zimbabwe  1987     9216418    62.351  706.157306
1700     Zimbabwe  1992    10704340    60.377  693.420786
1701     Zimbabwe  1997    11404948    46.809  792.449960
1702     Zimbabwe  2002    11926563    39.989  672.038623
1703     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [ ]:
df['year+7']=df['year']+7
df

          Country  year  Population  life_exp     gdp_cap  year+7
0     Afghanistan  1952     8425333    28.801  779.445314    1959
1     Afghanistan  1957     9240934    30.332  820.853030    1964
2     Afghanistan  1962    10267083    31.997  853.100710    1969
3     Afghanistan  1967    11537966    34.020  836.197138    1974
4     Afghanistan  1972    13079460    36.088  739.981106    1979
...           ...   ...         ...       ...         ...     ...
1699     Zimbabwe  1987     9216418    62.351  706.157306    1994
1700     Zimbabwe  1992    10704340    60.377  693.420786    1999
1701     Zimbabwe  1997    11404948    46.809  792.449960    2004
1702     Zimbabwe  2002    11926563    39.989  672.038623    2009
1703     Zimbabwe  2007    12311143    43.487  469.709298    2014

[1704 rows x 6 columns]

In [ ]:
df['gdp'] = df['gdp_cap']*df['Population']
df

,Country,year,Population,life_exp,gdp_cap,year+7,gdp
0,Afghanistan,1952,8425333,28.801,779.445314,1959,6.567086e+09
1,Afghanistan,1957,9240934,30.332,820.853030,1964,7.585449e+09
2,Afghanistan,1962,10267083,31.997,853.100710,1969,8.758856e+09
3,Afghanistan,1967,11537966,34.020,836.197138,1974,9.648014e+09
4,Afghanistan,1972,13079460,36.088,739.981106,1979,9.678553e+09
...,...,...,...,...,...,...,...
1699,Zimbabwe,1987,9216418,62.351,706.157306,1994,6.508241e+09
1700,Zimbabwe,1992,10704340,60.377,693.420786,1999,7.422612e+09
1701,Zimbabwe,1997,11404948,46.809,792.449960,2004,9.037851e+09
1702,Zimbabwe,2002,11926563,39.989,672.038623,2009,8.015111e+09
1703,Zimbabwe,2007,12311143,43.487,469.709298,2014,5.782658e+09

In [ ]:
#missing values ?? => deal with mission values. => pandas
df['new_column'] = ''
df

,Country,year,Population,life_exp,gdp_cap,year+7,gdp,new_column
0,Afghanistan,1952,8425333,28.801,779.445314,1959,6.567086e+09,
1,Afghanistan,1957,9240934,30.332,820.853030,1964,7.585449e+09,
2,Afghanistan,1962,10267083,31.997,853.100710,1969,8.758856e+09,
3,Afghanistan,1967,11537966,34.020,836.197138,1974,9.648014e+09,
4,Afghanistan,1972,13079460,36.088,739.981106,1979,9.678553e+09,
...,...,...,...,...,...,...,...,...
1699,Zimbabwe,1987,9216418,62.351,706.157306,1994,6.508241e+09,
1700,Zimbabwe,1992,10704340,60.377,693.420786,1999,7.422612e+09,
1701,Zimbabwe,1997,11404948,46.809,792.449960,2004,9.037851e+09,
1702,Zimbabwe,2002,11926563,39.989,672.038623,2009,8.015111e+09,
1703,Zimbabwe,2007,12311143,43.487,469.709298,2014,5.782658e+09,

In [ ]:
df['Own'] = [i for i in range(1704)]
df

,Country,year,Population,life_exp,gdp_cap,year+7,gdp,new_column,Own
0,Afghanistan,1952,8425333,28.801,779.445314,1959,6.567086e+09,,0
1,Afghanistan,1957,9240934,30.332,820.853030,1964,7.585449e+09,,1
2,Afghanistan,1962,10267083,31.997,853.100710,1969,8.758856e+09,,2
3,Afghanistan,1967,11537966,34.020,836.197138,1974,9.648014e+09,,3
4,Afghanistan,1972,13079460,36.088,739.981106,1979,9.678553e+09,,4
...,...,...,...,...,...,...,...,...,...
1699,Zimbabwe,1987,9216418,62.351,706.157306,1994,6.508241e+09,,1699
1700,Zimbabwe,1992,10704340,60.377,693.420786,1999,7.422612e+09,,1700
1701,Zimbabwe,1997,11404948,46.809,792.449960,2004,9.037851e+09,,1701
1702,Zimbabwe,2002,11926563,39.989,672.038623,2009,8.015111e+09,,1702
1703,Zimbabwe,2007,12311143,43.487,469.709298,2014,5.782658e+09,,1703

In [ ]:
df.drop(columns = ['year+7','Own','gdp','new_column'],inplace=True)
df

          Country  year  Population  life_exp     gdp_cap
0     Afghanistan  1952     8425333    28.801  779.445314
1     Afghanistan  1957     9240934    30.332  820.853030
2     Afghanistan  1962    10267083    31.997  853.100710
3     Afghanistan  1967    11537966    34.020  836.197138
4     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1699     Zimbabwe  1987     9216418    62.351  706.157306
1700     Zimbabwe  1992    10704340    60.377  693.420786
1701     Zimbabwe  1997    11404948    46.809  792.449960
1702     Zimbabwe  2002    11926563    39.989  672.038623
1703     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [ ]:
#Given a dataframe consisting of 5 columns, which is the correct code to drop the 3rd column from the start?
df

          Country  year  Population  life_exp     gdp_cap
0     Afghanistan  1952     8425333    28.801  779.445314
1     Afghanistan  1957     9240934    30.332  820.853030
2     Afghanistan  1962    10267083    31.997  853.100710
3     Afghanistan  1967    11537966    34.020  836.197138
4     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1699     Zimbabwe  1987     9216418    62.351  706.157306
1700     Zimbabwe  1992    10704340    60.377  693.420786
1701     Zimbabwe  1997    11404948    46.809  792.449960
1702     Zimbabwe  2002    11926563    39.989  672.038623
1703     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [ ]:
#basics operations on rows
df

          Country  year  Population  life_exp     gdp_cap
0     Afghanistan  1952     8425333    28.801  779.445314
1     Afghanistan  1957     9240934    30.332  820.853030
2     Afghanistan  1962    10267083    31.997  853.100710
3     Afghanistan  1967    11537966    34.020  836.197138
4     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1699     Zimbabwe  1987     9216418    62.351  706.157306
1700     Zimbabwe  1992    10704340    60.377  693.420786
1701     Zimbabwe  1997    11404948    46.809  792.449960
1702     Zimbabwe  2002    11926563    39.989  672.038623
1703     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [ ]:
df.index

RangeIndex(start=0, stop=1704, step=1)

In [ ]:
df.index = list(range(1,1705))

In [ ]:
df.shape

(1704, 5)

In [ ]:
df.index = list(range(1,df.shape[0]+1))

In [ ]:
df

          Country  year  Population  life_exp     gdp_cap
1     Afghanistan  1952     8425333    28.801  779.445314
2     Afghanistan  1957     9240934    30.332  820.853030
3     Afghanistan  1962    10267083    31.997  853.100710
4     Afghanistan  1967    11537966    34.020  836.197138
5     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1700     Zimbabwe  1987     9216418    62.351  706.157306
1701     Zimbabwe  1992    10704340    60.377  693.420786
1702     Zimbabwe  1997    11404948    46.809  792.449960
1703     Zimbabwe  2002    11926563    39.989  672.038623
1704     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [ ]:
#explicit and implicit indexes
df

          Country  year  Population  life_exp     gdp_cap
1     Afghanistan  1952     8425333    28.801  779.445314
2     Afghanistan  1957     9240934    30.332  820.853030
3     Afghanistan  1962    10267083    31.997  853.100710
4     Afghanistan  1967    11537966    34.020  836.197138
5     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1700     Zimbabwe  1987     9216418    62.351  706.157306
1701     Zimbabwe  1992    10704340    60.377  693.420786
1702     Zimbabwe  1997    11404948    46.809  792.449960
1703     Zimbabwe  2002    11926563    39.989  672.038623
1704     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [ ]:
df['hina']

KeyError: 'hina'

In [ ]:
df[0] #indexing

KeyError: 0

In [ ]:
df[1] #serach for columns

KeyError: 1

In [ ]:
df

          Country  year  Population  life_exp     gdp_cap
1     Afghanistan  1952     8425333    28.801  779.445314
2     Afghanistan  1957     9240934    30.332  820.853030
3     Afghanistan  1962    10267083    31.997  853.100710
4     Afghanistan  1967    11537966    34.020  836.197138
5     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1700     Zimbabwe  1987     9216418    62.351  706.157306
1701     Zimbabwe  1992    10704340    60.377  693.420786
1702     Zimbabwe  1997    11404948    46.809  792.449960
1703     Zimbabwe  2002    11926563    39.989  672.038623
1704     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [ ]:
#slicing
df[0:4] #starting 4 rows #head(n) => df[0:5/n]

       Country  year  Population  life_exp     gdp_cap
1  Afghanistan  1952     8425333    28.801  779.445314
2  Afghanistan  1957     9240934    30.332  820.853030
3  Afghanistan  1962    10267083    31.997  853.100710
4  Afghanistan  1967    11537966    34.020  836.197138

In [ ]:
import numpy as np
df.index = np.arange(1,df.shape[0]+1,dtype='float')
df

            Country  year  Population  life_exp     gdp_cap
1.0     Afghanistan  1952     8425333    28.801  779.445314
2.0     Afghanistan  1957     9240934    30.332  820.853030
3.0     Afghanistan  1962    10267083    31.997  853.100710
4.0     Afghanistan  1967    11537966    34.020  836.197138
5.0     Afghanistan  1972    13079460    36.088  739.981106
...             ...   ...         ...       ...         ...
1700.0     Zimbabwe  1987     9216418    62.351  706.157306
1701.0     Zimbabwe  1992    10704340    60.377  693.420786
1702.0     Zimbabwe  1997    11404948    46.809  792.449960
1703.0     Zimbabwe  2002    11926563    39.989  672.038623
1704.0     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [ ]:
sample = df.head()
sample

         Country  year  Population  life_exp     gdp_cap
1.0  Afghanistan  1952     8425333    28.801  779.445314
2.0  Afghanistan  1957     9240934    30.332  820.853030
3.0  Afghanistan  1962    10267083    31.997  853.100710
4.0  Afghanistan  1967    11537966    34.020  836.197138
5.0  Afghanistan  1972    13079460    36.088  739.981106

In [ ]:
#string indices
sample.index = ['a','b','c','d','e']
sample

       Country  year  Population  life_exp     gdp_cap
a  Afghanistan  1952     8425333    28.801  779.445314
b  Afghanistan  1957     9240934    30.332  820.853030
c  Afghanistan  1962    10267083    31.997  853.100710
d  Afghanistan  1967    11537966    34.020  836.197138
e  Afghanistan  1972    13079460    36.088  739.981106

In [ ]:
df.index = np.arange(1,df.shape[0]+1,dtype='int')
df

          Country  year  Population  life_exp     gdp_cap
1     Afghanistan  1952     8425333    28.801  779.445314
2     Afghanistan  1957     9240934    30.332  820.853030
3     Afghanistan  1962    10267083    31.997  853.100710
4     Afghanistan  1967    11537966    34.020  836.197138
5     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1700     Zimbabwe  1987     9216418    62.351  706.157306
1701     Zimbabwe  1992    10704340    60.377  693.420786
1702     Zimbabwe  1997    11404948    46.809  792.449960
1703     Zimbabwe  2002    11926563    39.989  672.038623
1704     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [ ]:
ser = df['Country']
ser
#access any row from this series

1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
5       Afghanistan
           ...
1700       Zimbabwe
1701       Zimbabwe
1702       Zimbabwe
1703       Zimbabwe
1704       Zimbabwe
Name: Country, Length: 1704, dtype: object

In [ ]:
ser.head(20)

1     Afghanistan
2     Afghanistan
3     Afghanistan
4     Afghanistan
5     Afghanistan
6     Afghanistan
7     Afghanistan
8     Afghanistan
9     Afghanistan
10    Afghanistan
11    Afghanistan
12    Afghanistan
13        Albania
14        Albania
15        Albania
16        Albania
17        Albania
18        Albania
19        Albania
20        Albania
Name: Country, dtype: object

In [ ]:
ser[2]

'Afghanistan'

In [ ]:
ser[12]

'Afghanistan'

In [ ]:
ser[13]

'Albania'

In [ ]:
ser[0] #explicit indexing

KeyError: 0

In [ ]:
ser.head(20)

1     Afghanistan
2     Afghanistan
3     Afghanistan
4     Afghanistan
5     Afghanistan
6     Afghanistan
7     Afghanistan
8     Afghanistan
9     Afghanistan
10    Afghanistan
11    Afghanistan
12    Afghanistan
13        Albania
14        Albania
15        Albania
16        Albania
17        Albania
18        Albania
19        Albania
20        Albania
Name: Country, dtype: object

In [ ]:
ser[6:16] #implicit indexzing

7     Afghanistan
8     Afghanistan
9     Afghanistan
10    Afghanistan
11    Afghanistan
12    Afghanistan
13        Albania
14        Albania
15        Albania
16        Albania
Name: Country, dtype: object

In [ ]:
df

          Country  year  Population  life_exp     gdp_cap
1     Afghanistan  1952     8425333    28.801  779.445314
2     Afghanistan  1957     9240934    30.332  820.853030
3     Afghanistan  1962    10267083    31.997  853.100710
4     Afghanistan  1967    11537966    34.020  836.197138
5     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1700     Zimbabwe  1987     9216418    62.351  706.157306
1701     Zimbabwe  1992    10704340    60.377  693.420786
1702     Zimbabwe  1997    11404948    46.809  792.449960
1703     Zimbabwe  2002    11926563    39.989  672.038623
1704     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [ ]:
df.loc[1] #.loc => explicit index

Country       Afghanistan
year                 1952
Population        8425333
life_exp           28.801
gdp_cap        779.445314
Name: 1, dtype: object

In [ ]:
df.iloc[0] #.iloc => implict index

Country       Afghanistan
year                 1952
Population        8425333
life_exp           28.801
gdp_cap        779.445314
Name: 1, dtype: object

In [ ]:
df

          Country  year  Population  life_exp     gdp_cap
1     Afghanistan  1952     8425333    28.801  779.445314
2     Afghanistan  1957     9240934    30.332  820.853030
3     Afghanistan  1962    10267083    31.997  853.100710
4     Afghanistan  1967    11537966    34.020  836.197138
5     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1700     Zimbabwe  1987     9216418    62.351  706.157306
1701     Zimbabwe  1992    10704340    60.377  693.420786
1702     Zimbabwe  1997    11404948    46.809  792.449960
1703     Zimbabwe  2002    11926563    39.989  672.038623
1704     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [ ]:
#second diff
df.iloc[1]

Country       Afghanistan
year                 1957
Population        9240934
life_exp           30.332
gdp_cap         820.85303
Name: 2, dtype: object

In [ ]:
#slicing
df.iloc[3:5]

       Country  year  Population  life_exp     gdp_cap
4  Afghanistan  1967    11537966    34.020  836.197138
5  Afghanistan  1972    13079460    36.088  739.981106

In [ ]:
df.loc[3:5]

       Country  year  Population  life_exp     gdp_cap
3  Afghanistan  1962    10267083    31.997  853.100710
4  Afghanistan  1967    11537966    34.020  836.197138
5  Afghanistan  1972    13079460    36.088  739.981106

In [ ]:
df.index = list or np

Index([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
       ...
       1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704],
      dtype='int64', length=1704)

In [ ]:
df['Population'][1700]

np.int64(9216418)

In [7]:
pd.DataFrame(df, columns=['time', 'total_bill', 'tip'])

       time  total_bill   tip
0    Dinner       16.99  1.01
1    Dinner       10.34  1.66
2    Dinner       21.01  3.50
3    Dinner       23.68  3.31
4    Dinner       24.59  3.61
..      ...         ...   ...
239  Dinner       29.03  5.92
240  Dinner       27.18  2.00
241  Dinner       22.67  2.00
242  Dinner       17.82  1.75
243  Dinner       18.78  3.00

[244 rows x 3 columns]

In [8]:
df[['time', 'total_bill', 'tip']]

       time  total_bill   tip
0    Dinner       16.99  1.01
1    Dinner       10.34  1.66
2    Dinner       21.01  3.50
3    Dinner       23.68  3.31
4    Dinner       24.59  3.61
..      ...         ...   ...
239  Dinner       29.03  5.92
240  Dinner       27.18  2.00
241  Dinner       22.67  2.00
242  Dinner       17.82  1.75
243  Dinner       18.78  3.00

[244 rows x 3 columns]

In [9]:
df.loc[:, ['time', 'total_bill', 'tip']]

       time  total_bill   tip
0    Dinner       16.99  1.01
1    Dinner       10.34  1.66
2    Dinner       21.01  3.50
3    Dinner       23.68  3.31
4    Dinner       24.59  3.61
..      ...         ...   ...
239  Dinner       29.03  5.92
240  Dinner       27.18  2.00
241  Dinner       22.67  2.00
242  Dinner       17.82  1.75
243  Dinner       18.78  3.00

[244 rows x 3 columns]

In [10]:
df.iloc[:,0:2]

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [11]:
df.iloc[:2,:2]

   total_bill   tip
0       16.99  1.01
1       10.34  1.66

In [15]:
df.loc[:2,"sex":"day"]

      sex smoker  day
0  Female     No  Sun
1    Male     No  Sun
2    Male     No  Sun

In [18]:
data = pd.read_csv('mtcars.csv') #storing the data in df

In [19]:
data.iloc[1:5, 3:5]

    disp   hp
1  160.0  110
2  108.0   93
3  258.0  110
4  360.0  175

In [20]:
data.iloc[1:4, 3:4]

    disp
1  160.0
2  108.0
3  258.0

In [22]:
data.loc[1:6, 3:6]

TypeError: cannot do slice indexing on Index with these indexers [3] of type int

In [24]:
data.unique()

AttributeError: 'DataFrame' object has no attribute 'unique'

In [2]:
data = pd.read_csv('mtcars.csv') #storing the data in df
data

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [3]:
data.loc[:,'disp']

0     160.0
1     160.0
2     108.0
3     258.0
4     360.0
5     225.0
6     360.0
7     146.7
8     140.8
9     167.6
10    167.6
11    275.8
12    275.8
13    275.8
14    472.0
15    460.0
16    440.0
17     78.7
18     75.7
19     71.1
20    120.1
21    318.0
22    304.0
23    350.0
24    400.0
25     79.0
26    120.3
27     95.1
28    351.0
29    145.0
30    301.0
31    121.0
Name: disp, dtype: float64

In [4]:
data['disp']

0     160.0
1     160.0
2     108.0
3     258.0
4     360.0
5     225.0
6     360.0
7     146.7
8     140.8
9     167.6
10    167.6
11    275.8
12    275.8
13    275.8
14    472.0
15    460.0
16    440.0
17     78.7
18     75.7
19     71.1
20    120.1
21    318.0
22    304.0
23    350.0
24    400.0
25     79.0
26    120.3
27     95.1
28    351.0
29    145.0
30    301.0
31    121.0
Name: disp, dtype: float64

In [6]:
data.loc['disp',:]

KeyError: 'disp'