In [ ]:
!wget "https://drive.google.com/uc?export=download&id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_" -O mckinsey.csv

--2026-03-05 03:08:27--  https://drive.google.com/uc?export=download&id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_
Resolving drive.google.com (drive.google.com)... 173.194.212.102, 173.194.212.100, 173.194.212.139, ...
Connecting to drive.google.com (drive.google.com)|173.194.212.102|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_&export=download [following]
--2026-03-05 03:08:27--  https://drive.usercontent.google.com/download?id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 173.194.210.132, 2607:f8b0:400c:c0f::84
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|173.194.210.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 83785 (82K) [application/octet-stream]
Saving to: ‘mckinsey.csv’

mckinsey.csv        100%[===================>]  81.82K  --.-KB/s    in 0.001s

2026-03-05 03:08:28 (86.9 MB/s) - ‘mckinsey.csv’ saved [83785/83785]

In [ ]:
import pandas as pd
df=pd.read_csv("mckinsey.csv")

In [ ]:
df.head(20)

        country  year  population continent  life_exp      gdp_cap
0   Afghanistan  1952     8425333      Asia    28.801   779.445314
1   Afghanistan  1957     9240934      Asia    30.332   820.853030
2   Afghanistan  1962    10267083      Asia    31.997   853.100710
3   Afghanistan  1967    11537966      Asia    34.020   836.197138
4   Afghanistan  1972    13079460      Asia    36.088   739.981106
5   Afghanistan  1977    14880372      Asia    38.438   786.113360
6   Afghanistan  1982    12881816      Asia    39.854   978.011439
7   Afghanistan  1987    13867957      Asia    40.822   852.395945
8   Afghanistan  1992    16317921      Asia    41.674   649.341395
9   Afghanistan  1997    22227415      Asia    41.763   635.341351
10  Afghanistan  2002    25268405      Asia    42.129   726.734055
11  Afghanistan  2007    31889923      Asia    43.828   974.580338
12      Albania  1952     1282697    Europe    55.230  1601.056136
13      Albania  1957     1476505    Europe    59.280  1942.284244
14      Albania  1962     1728137    Europe    64.820  2312.888958
15      Albania  1967     1984060    Europe    66.220  2760.196931
16      Albania  1972     2263554    Europe    67.690  3313.422188
17      Albania  1977     2509048    Europe    68.930  3533.003910
18      Albania  1982     2780097    Europe    70.420  3630.880722
19      Albania  1987     3075321    Europe    72.000  3738.932735

In [ ]:
df.iloc[:20]

        country  year  population continent  life_exp      gdp_cap
0   Afghanistan  1952     8425333      Asia    28.801   779.445314
1   Afghanistan  1957     9240934      Asia    30.332   820.853030
2   Afghanistan  1962    10267083      Asia    31.997   853.100710
3   Afghanistan  1967    11537966      Asia    34.020   836.197138
4   Afghanistan  1972    13079460      Asia    36.088   739.981106
5   Afghanistan  1977    14880372      Asia    38.438   786.113360
6   Afghanistan  1982    12881816      Asia    39.854   978.011439
7   Afghanistan  1987    13867957      Asia    40.822   852.395945
8   Afghanistan  1992    16317921      Asia    41.674   649.341395
9   Afghanistan  1997    22227415      Asia    41.763   635.341351
10  Afghanistan  2002    25268405      Asia    42.129   726.734055
11  Afghanistan  2007    31889923      Asia    43.828   974.580338
12      Albania  1952     1282697    Europe    55.230  1601.056136
13      Albania  1957     1476505    Europe    59.280  1942.284244
14      Albania  1962     1728137    Europe    64.820  2312.888958
15      Albania  1967     1984060    Europe    66.220  2760.196931
16      Albania  1972     2263554    Europe    67.690  3313.422188
17      Albania  1977     2509048    Europe    68.930  3533.003910
18      Albania  1982     2780097    Europe    70.420  3630.880722
19      Albania  1987     3075321    Europe    72.000  3738.932735

In [ ]:
df.head()

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [ ]:
pd.DataFrame(df, columns=['year', 'life_exp', 'gdp_cap'])

      year  life_exp     gdp_cap
0     1952    28.801  779.445314
1     1957    30.332  820.853030
2     1962    31.997  853.100710
3     1967    34.020  836.197138
4     1972    36.088  739.981106
...    ...       ...         ...
1699  1987    62.351  706.157306
1700  1992    60.377  693.420786
1701  1997    46.809  792.449960
1702  2002    39.989  672.038623
1703  2007    43.487  469.709298

[1704 rows x 3 columns]

In [ ]:
df[['year', 'life_exp', 'gdp_cap']]

      year  life_exp     gdp_cap
0     1952    28.801  779.445314
1     1957    30.332  820.853030
2     1962    31.997  853.100710
3     1967    34.020  836.197138
4     1972    36.088  739.981106
...    ...       ...         ...
1699  1987    62.351  706.157306
1700  1992    60.377  693.420786
1701  1997    46.809  792.449960
1702  2002    39.989  672.038623
1703  2007    43.487  469.709298

[1704 rows x 3 columns]

In [ ]:
df.loc[:,['year', 'life_exp', 'gdp_cap']]

      year  life_exp     gdp_cap
0     1952    28.801  779.445314
1     1957    30.332  820.853030
2     1962    31.997  853.100710
3     1967    34.020  836.197138
4     1972    36.088  739.981106
...    ...       ...         ...
1699  1987    62.351  706.157306
1700  1992    60.377  693.420786
1701  1997    46.809  792.449960
1702  2002    39.989  672.038623
1703  2007    43.487  469.709298

[1704 rows x 3 columns]

In [ ]:
df.iloc[:,0:2]

          country  year
0     Afghanistan  1952
1     Afghanistan  1957
2     Afghanistan  1962
3     Afghanistan  1967
4     Afghanistan  1972
...           ...   ...
1699     Zimbabwe  1987
1700     Zimbabwe  1992
1701     Zimbabwe  1997
1702     Zimbabwe  2002
1703     Zimbabwe  2007

[1704 rows x 2 columns]

In [ ]:
df.iloc[:,0:4]

          country  year  population continent
0     Afghanistan  1952     8425333      Asia
1     Afghanistan  1957     9240934      Asia
2     Afghanistan  1962    10267083      Asia
3     Afghanistan  1967    11537966      Asia
4     Afghanistan  1972    13079460      Asia
...           ...   ...         ...       ...
1699     Zimbabwe  1987     9216418    Africa
1700     Zimbabwe  1992    10704340    Africa
1701     Zimbabwe  1997    11404948    Africa
1702     Zimbabwe  2002    11926563    Africa
1703     Zimbabwe  2007    12311143    Africa

[1704 rows x 4 columns]

In [ ]:
df.nunique()

country        142
year            12
population    1704
continent        5
life_exp      1626
gdp_cap       1704
dtype: int64

In [ ]:
df['country'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
       'Australia', 'Austria', 'Bahrain', 'Bangladesh', 'Belgium',
       'Benin', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon',
       'Canada', 'Central African Republic', 'Chad', 'Chile', 'China',
       'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Czech Republic',
       'Denmark', 'Djibouti', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Ethiopia',
       'Finland', 'France', 'Gabon', 'Gambia', 'Germany', 'Ghana',
       'Greece', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Haiti',
       'Honduras', 'Hong Kong, China', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kenya', 'Korea, Dem. Rep.',
       'Korea, Rep.', 'Kuwait', 'Lebanon', 'Lesotho', 'Liberia', 'Libya',
       'Madagascar', 'Malawi', 'Malaysia', 'Mali', 'Mauritania',
       'Mauritius', 'Mexico', 'Mongolia', 'Montenegro', 'Morocco',
       'Mozambique', 'Myanmar', 'Namibia', 'Nepal', 'Netherlands',
       'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Norway', 'Oman',
       'Pakistan', 'Panama', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Puerto Rico', 'Reunion', 'Romania', 'Rwanda',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Sierra Leone', 'Singapore', 'Slovak Republic', 'Slovenia',
       'Somalia', 'South Africa', 'Spain', 'Sri Lanka', 'Sudan',
       'Swaziland', 'Sweden', 'Switzerland', 'Syria', 'Taiwan',
       'Tanzania', 'Thailand', 'Togo', 'Trinidad and Tobago', 'Tunisia',
       'Turkey', 'Uganda', 'United Kingdom', 'United States', 'Uruguay',
       'Venezuela', 'Vietnam', 'West Bank and Gaza', 'Yemen, Rep.',
       'Zambia', 'Zimbabwe'], dtype=object)

In [ ]:
!wget "https://drive.google.com/file/d/1UViHcT4lKDsTfc97gBqIvds25uHe4b5e/view?usp=drive_link" -O sales.csv

--2026-03-05 04:53:21--  https://drive.google.com/file/d/1UViHcT4lKDsTfc97gBqIvds25uHe4b5e/view?usp=drive_link
Resolving drive.google.com (drive.google.com)... 74.125.26.139, 74.125.26.138, 74.125.26.102, ...
Connecting to drive.google.com (drive.google.com)|74.125.26.139|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘sales.csv’

sales.csv               [ <=>                ]  58.70K  --.-KB/s    in 0s

2026-03-05 04:53:21 (119 MB/s) - ‘sales.csv’ saved [60108]

In [ ]:
import pandas as pd

df=pd.read_csv("sales.csv")


#print(result)

ParserError: Error tokenizing data. C error: Expected 1 fields in line 3, saw 5336

In [ ]:
!wget https://drive.google.com/file/d/1UViHcT4lKDsTfc97gBqIvds25uHe4b5e/view?usp=drive_link -O stock.csv

--2026-03-05 07:35:45--  https://drive.google.com/file/d/1UViHcT4lKDsTfc97gBqIvds25uHe4b5e/view?usp=drive_link
Resolving drive.google.com (drive.google.com)... 173.194.210.139, 173.194.210.100, 173.194.210.101, ...
Connecting to drive.google.com (drive.google.com)|173.194.210.139|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘stock.csv’

stock.csv               [ <=>                ] 114.65K  --.-KB/s    in 0.006s

2026-03-05 07:35:46 (20.0 MB/s) - ‘stock.csv’ saved [117401]

In [ ]:
import pandas as pd
dfstock=pd.read_csv("stock.csv")

ParserError: Error tokenizing data. C error: Expected 1 fields in line 3, saw 5363

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
dfstock=pd.read_csv("/content/stock.csv")

ParserError: Error tokenizing data. C error: Expected 1 fields in line 3, saw 5369

In [ ]:
https://drive.google.com/file/d/1UViHcT4lKDsTfc97gBqIvds25uHe4b5e/view?usp=drive_link