<a href="https://colab.research.google.com/github/mitrasubham/learn-ml/blob/main/pandas_3_class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!wget "https://drive.google.com/uc?export=download&id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_" -O mckinsey.csv

--2026-03-10 04:14:29--  https://drive.google.com/uc?export=download&id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_
Resolving drive.google.com (drive.google.com)... 142.250.141.102, 142.250.141.139, 142.250.141.100, ...
Connecting to drive.google.com (drive.google.com)|142.250.141.102|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_&export=download [following]
--2026-03-10 04:14:29--  https://drive.usercontent.google.com/download?id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.251.2.132, 2607:f8b0:4023:c0d::84
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.251.2.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 83785 (82K) [application/octet-stream]
Saving to: ‘mckinsey.csv’

mckinsey.csv        100%[===================>]  81.82K  --.-KB/s    in 0.03s

2026-03-10 04:14:30 (2.70 MB/s) - ‘mckinsey.csv’ saved [83785/83785]

Handling Duplicates

In [2]:
import pandas as pd
df = pd.read_csv('mckinsey.csv')
df.head()

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [3]:
df.shape

(1704, 6)

In [4]:
df.loc[len(df.index)] = ['India', 2000, 13500000, 'Asia', 37.08, 900.23]
df.loc[len(df.index)] = ['Sri Lanka',2022 ,130000000, 'Asia', 80.00,500.00]
df.loc[len(df.index)] = ['Sri Lanka',2022 ,130000000, 'Asia', 80.00,500.00]
df.loc[len(df.index)] = ['India',2000 ,13500000, 'Asia', 80.00,900.23]

In [6]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1703    False
1704    False
1705    False
1706     True
1707    False
Length: 1708, dtype: bool

In [7]:
df.loc[df.duplicated()]

        country  year  population continent  life_exp  gdp_cap
1706  Sri Lanka  2022   130000000      Asia      80.0    500.0

In [8]:
df1=df[df["country"]=="India"]

In [9]:
df1

     country  year  population continent  life_exp      gdp_cap
696    India  1952   372000000      Asia    37.373   546.565749
697    India  1957   409000000      Asia    40.249   590.061996
698    India  1962   454000000      Asia    43.605   658.347151
699    India  1967   506000000      Asia    47.193   700.770611
700    India  1972   567000000      Asia    50.651   724.032527
701    India  1977   634000000      Asia    54.208   813.337323
702    India  1982   708000000      Asia    56.596   855.723538
703    India  1987   788000000      Asia    58.553   976.512676
704    India  1992   872000000      Asia    60.223  1164.406809
705    India  1997   959000000      Asia    61.765  1458.817442
706    India  2002  1034172547      Asia    62.879  1746.769454
707    India  2007  1110396331      Asia    64.698  2452.210407
1704   India  2000    13500000      Asia    37.080   900.230000
1707   India  2000    13500000      Asia    80.000   900.230000

In [10]:
df1.drop_duplicates(keep=False)

     country  year  population continent  life_exp      gdp_cap
696    India  1952   372000000      Asia    37.373   546.565749
697    India  1957   409000000      Asia    40.249   590.061996
698    India  1962   454000000      Asia    43.605   658.347151
699    India  1967   506000000      Asia    47.193   700.770611
700    India  1972   567000000      Asia    50.651   724.032527
701    India  1977   634000000      Asia    54.208   813.337323
702    India  1982   708000000      Asia    56.596   855.723538
703    India  1987   788000000      Asia    58.553   976.512676
704    India  1992   872000000      Asia    60.223  1164.406809
705    India  1997   959000000      Asia    61.765  1458.817442
706    India  2002  1034172547      Asia    62.879  1746.769454
707    India  2007  1110396331      Asia    64.698  2452.210407
1704   India  2000    13500000      Asia    37.080   900.230000
1707   India  2000    13500000      Asia    80.000   900.230000

In [11]:
df.drop_duplicates(keep="first")

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298
1704        India  2000    13500000      Asia    37.080  900.230000
1705    Sri Lanka  2022   130000000      Asia    80.000  500.000000
1707        India  2000    13500000      Asia    80.000  900.230000

[1707 rows x 6 columns]

In [12]:
df.duplicated().sum()

np.int64(1)

In [13]:
df[df["country"]== "Sri Lanka"]

        country  year  population continent  life_exp      gdp_cap
1428  Sri Lanka  1952     7982342      Asia    57.593  1083.532030
1429  Sri Lanka  1957     9128546      Asia    61.456  1072.546602
1430  Sri Lanka  1962    10421936      Asia    62.192  1074.471960
1431  Sri Lanka  1967    11737396      Asia    64.266  1135.514326
1432  Sri Lanka  1972    13016733      Asia    65.042  1213.395530
1433  Sri Lanka  1977    14116836      Asia    65.949  1348.775651
1434  Sri Lanka  1982    15410151      Asia    68.757  1648.079789
1435  Sri Lanka  1987    16495304      Asia    69.011  1876.766827
1436  Sri Lanka  1992    17587060      Asia    70.379  2153.739222
1437  Sri Lanka  1997    18698655      Asia    70.457  2664.477257
1438  Sri Lanka  2002    19576783      Asia    70.815  3015.378833
1439  Sri Lanka  2007    20378239      Asia    72.396  3970.095407
1705  Sri Lanka  2022   130000000      Asia    80.000   500.000000
1706  Sri Lanka  2022   130000000      Asia    80.000   500.000000

In [15]:
df[df["country"]== "Sri Lanka"].duplicated().sum()

np.int64(1)

Sorting

In [16]:
df.sort_values(by="year",ascending=True)

          country  year  population continent  life_exp       gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801    779.445314
312       Comoros  1952      153936    Africa    40.715   1102.990936
1692     Zimbabwe  1952     3080907    Africa    48.451    406.884115
336   Congo, Rep.  1952      854885    Africa    42.111   2125.621418
12        Albania  1952     1282697    Europe    55.230   1601.056136
...           ...   ...         ...       ...       ...           ...
1703     Zimbabwe  2007    12311143    Africa    43.487    469.709298
851   Korea, Rep.  2007    49044790      Asia    78.623  23348.139730
1691       Zambia  2007    11746035    Africa    42.384   1271.211593
1705    Sri Lanka  2022   130000000      Asia    80.000    500.000000
1706    Sri Lanka  2022   130000000      Asia    80.000    500.000000

[1708 rows x 6 columns]

In [17]:
df.sort_values(by="year",ascending=False)

,country,year,population,continent,life_exp,gdp_cap
1705,Sri Lanka,2022,130000000,Asia,80.000,500.000000
1706,Sri Lanka,2022,130000000,Asia,80.000,500.000000
1691,Zambia,2007,11746035,Africa,42.384,1271.211593
11,Afghanistan,2007,31889923,Asia,43.828,974.580338
503,Eritrea,2007,4906585,Africa,58.040,641.369524
...,...,...,...,...,...,...
996,Mongolia,1952,800663,Asia,42.244,786.566857
252,Central African Republic,1952,1291695,Africa,35.463,1071.310713
36,Angola,1952,4232095,Africa,30.015,3520.610273
1692,Zimbabwe,1952,3080907,Africa,48.451,406.884115
0,Afghanistan,1952,8425333,Asia,28.801,779.445314

In [19]:
#multiple columns
df.sort_values(by=['year','life_exp'])

               country  year  population continent  life_exp       gdp_cap
0          Afghanistan  1952     8425333      Asia    28.801    779.445314
552             Gambia  1952      284320    Africa    30.000    485.230659
36              Angola  1952     4232095    Africa    30.015   3520.610273
1344      Sierra Leone  1952     2143249    Africa    30.331    879.787736
1032        Mozambique  1952     6446316    Africa    31.286    468.526038
...                ...   ...         ...       ...       ...           ...
695            Iceland  2007      301931    Europe    81.757  36180.789190
671   Hong Kong, China  2007     6980412      Asia    82.208  39724.978670
803              Japan  2007   127467972      Asia    82.603  31656.068060
1705         Sri Lanka  2022   130000000      Asia    80.000    500.000000
1706         Sri Lanka  2022   130000000      Asia    80.000    500.000000

[1708 rows x 6 columns]

In [20]:
df.sort_values(by=['year','life_exp'],ascending=[True,False])

          country  year  population continent  life_exp       gdp_cap
1140       Norway  1952     3327728    Europe    72.670  10095.421720
684       Iceland  1952      147962    Europe    72.490   7267.688428
1080  Netherlands  1952    10381988    Europe    72.130   8941.571858
1464       Sweden  1952     7124673    Europe    71.860   8527.844662
408       Denmark  1952     4334000    Europe    70.780   9692.385245
...           ...   ...         ...       ...       ...           ...
1691       Zambia  2007    11746035    Africa    42.384   1271.211593
1043   Mozambique  2007    19951656    Africa    42.082    823.685621
1463    Swaziland  2007     1133066    Africa    39.613   4513.480643
1705    Sri Lanka  2022   130000000      Asia    80.000    500.000000
1706    Sri Lanka  2022   130000000      Asia    80.000    500.000000

[1708 rows x 6 columns]

Concatenation

In [21]:
users = pd.DataFrame({"userid":[1, 2, 3], "name":["sharadh", "shahid", "khusalli"]})
users

   userid      name
0       1   sharadh
1       2    shahid
2       3  khusalli

In [22]:
msgs = pd.DataFrame({"userid":[1, 1, 2, 4], "msg":['hmm', "acha", "theek hai", "nice"]})
msgs

   userid        msg
0       1        hmm
1       1       acha
2       2  theek hai
3       4       nice

In [23]:
pd.concat([users,msgs],axis=0)

   userid      name        msg
0       1   sharadh        NaN
1       2    shahid        NaN
2       3  khusalli        NaN
0       1       NaN        hmm
1       1       NaN       acha
2       2       NaN  theek hai
3       4       NaN       nice

In [24]:
pd.concat([users,msgs],axis=1)

   userid      name  userid        msg
0     1.0   sharadh       1        hmm
1     2.0    shahid       1       acha
2     3.0  khusalli       2  theek hai
3     NaN       NaN       4       nice

In [25]:
df1=pd.DataFrame({'A':['apple','banana'],
                   'B':['x','y']})

In [26]:
df2=pd.DataFrame({'A':['mango','orange'],
                  'B':['p','q']})

In [27]:
pd.concat([df1,df2],axis=0)

        A  B
0   apple  x
1  banana  y
0   mango  p
1  orange  q

In [28]:
pd.concat([df1,df2],axis=1)

        A  B       A  B
0   apple  x   mango  p
1  banana  y  orange  q

Merge

In [29]:
pd.merge(users,msgs,on="userid",how="inner")

   userid     name        msg
0       1  sharadh        hmm
1       1  sharadh       acha
2       2   shahid  theek hai

In [30]:
pd.merge(users,msgs,on="userid",how="left")

   userid      name        msg
0       1   sharadh        hmm
1       1   sharadh       acha
2       2    shahid  theek hai
3       3  khusalli        NaN

In [31]:
pd.merge(users,msgs,on="userid",how="right")

   userid     name        msg
0       1  sharadh        hmm
1       1  sharadh       acha
2       2   shahid  theek hai
3       4      NaN       nice

In [32]:
pd.merge(users,msgs,on="userid",how="outer")

   userid      name        msg
0       1   sharadh        hmm
1       1   sharadh       acha
2       2    shahid  theek hai
3       3  khusalli        NaN
4       4       NaN       nice

In [33]:
temp_df = pd.merge(users, msgs, on="userid", how="inner")
print(temp_df)

   userid     name        msg
0       1  sharadh        hmm
1       1  sharadh       acha
2       2   shahid  theek hai

In [34]:
pd.merge(temp_df,msgs,on="userid",how="outer")

   userid     name      msg_x      msg_y
0       1  sharadh        hmm        hmm
1       1  sharadh        hmm       acha
2       1  sharadh       acha        hmm
3       1  sharadh       acha       acha
4       2   shahid  theek hai  theek hai
5       4      NaN        NaN       nice

users.columns
index(['userid', 'name'], dtype='object')

In [39]:
users

   id      name
0   1   sharadh
1   2    shahid
2   3  khusalli

In [37]:
users.columns=['id', 'name']

In [38]:
msgs

   userid        msg
0       1        hmm
1       1       acha
2       2  theek hai
3       4       nice

In [40]:
pd.merge(users,msgs,left_on="id",right_on="userid",how="inner")

   id     name  userid        msg
0   1  sharadh       1        hmm
1   1  sharadh       1       acha
2   2   shahid       2  theek hai

In [41]:
tempp_df=pd.merge(users,msgs,left_on="id",right_on="userid",how="left")

In [42]:
tempp_df

   id      name  userid        msg
0   1   sharadh     1.0        hmm
1   1   sharadh     1.0       acha
2   2    shahid     2.0  theek hai
3   3  khusalli     NaN        NaN

In [43]:
mask=tempp_df["msg"].isnull()

In [44]:
tempp_df[mask]

   id      name  userid  msg
3   3  khusalli     NaN  NaN

###Movie Dataset###

In [45]:
!gdown 1s2TkjSpzNc4SyxqRrQleZyDIHlc7bxnd
!gdown 1Ws-_s1fHZ9nHfGLVUQurbHDvStePlEJm

Downloading...
From: https://drive.google.com/uc?id=1s2TkjSpzNc4SyxqRrQleZyDIHlc7bxnd
To: /content/movies.csv
100% 112k/112k [00:00<00:00, 3.22MB/s]
Downloading...
From: https://drive.google.com/uc?id=1Ws-_s1fHZ9nHfGLVUQurbHDvStePlEJm
To: /content/directors.csv
100% 65.4k/65.4k [00:00<00:00, 3.83MB/s]

In [46]:
movies = pd.read_csv('movies.csv')

In [47]:
movies.head()

,Unnamed: 0,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
0,0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday
1,1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday
2,2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday
3,3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday
4,5,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday

In [48]:
movies.drop(columns="Unnamed: 0",inplace=True)

In [49]:
movies.head()

,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday
2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday

In [51]:
movies.shape

(1465, 11)

In [52]:
directors=pd.read_csv("directors.csv")

In [53]:
directors.head()

   Unnamed: 0      director_name    id gender
0           0      James Cameron  4762   Male
1           1     Gore Verbinski  4763   Male
2           2         Sam Mendes  4764   Male
3           3  Christopher Nolan  4765   Male
4           4     Andrew Stanton  4766   Male

In [54]:
directors.drop(columns="Unnamed: 0", inplace = True)
directors.head()

       director_name    id gender
0      James Cameron  4762   Male
1     Gore Verbinski  4763   Male
2         Sam Mendes  4764   Male
3  Christopher Nolan  4765   Male
4     Andrew Stanton  4766   Male

In [56]:
movies.head()

,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday
2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday

In [57]:
directors.head()

       director_name    id gender
0      James Cameron  4762   Male
1     Gore Verbinski  4763   Male
2         Sam Mendes  4764   Male
3  Christopher Nolan  4765   Male
4     Andrew Stanton  4766   Male

In [58]:
# How many unique directors i have in my movies df?
movies["director_id"].nunique()

199

In [59]:
directors["id"].nunique()

2349

In [60]:
# How can we check if all director_id values are present in id?
movies['director_id'].isin(directors['id'])

0       True
1       True
2       True
3       True
4       True
        ...
1460    True
1461    True
1462    True
1463    True
1464    True
Name: director_id, Length: 1465, dtype: bool

In [61]:
import numpy as np
np.all(movies['director_id'].isin(directors['id']))

np.True_

In [62]:
data = pd.merge(movies, directors, left_on = 'director_id', right_on = 'id', how="left")

In [63]:
data

,id_x,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day,director_name,id_y,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday,James Cameron,4762,Male
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday,Gore Verbinski,4763,Male
2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday,Sam Mendes,4764,Male
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday,Christopher Nolan,4765,Male
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday,Sam Raimi,4767,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,48363,0,3,321952,The Last Waltz,7.9,64,4809,1978,May,Monday,Martin Scorsese,4809,Male
1461,48370,27000,19,3151130,Clerks,7.4,755,5369,1994,Sep,Tuesday,Kevin Smith,5369,Male
1462,48375,0,7,0,Rampage,6.0,131,5148,2009,Aug,Friday,Uwe Boll,5148,Male
1463,48376,0,3,0,Slacker,6.4,77,5535,1990,Jul,Friday,Richard Linklater,5535,Male
1464,48395,220000,14,2040920,El Mariachi,6.6,238,5097,1992,Sep,Friday,Robert Rodriguez,5097,NaN